export const states = [
  { value: "Ariana", label: "Ariana" },
  { value: "Beja", label: "Béja" },
  { value: "BenArous", label: "Ben Arous" },
  { value: "Bizerte", label: "Bizerte" },
  { value: "Gabes", label: "Gabès" },
  { value: "Gafsa", label: "Gafsa" },
  { value: "Jendouba", label: "Jendouba" },
  { value: "Kairouan", label: "Kairouan" },
  { value: "Kasserine", label: "Kasserine" },
  { value: "Kebili", label: "Kébili" },
  { value: "LeKef", label: "Le Kef" },
  { value: "Mahdia", label: "Mahdia" },
  { value: "Manouba", label: "Manouba" },
  { value: "Medenine", label: "Médenine" },
  { value: "Monastir", label: "Monastir" },
  { value: "Nabeul", label: "Nabeul" },
  { value: "Sfax", label: "Sfax" },
  { value: "SidiBouzid", label: "Sidi Bouzid" },
  { value: "Siliana", label: "Siliana" },
  { value: "Sousse", label: "Sousse" },
  { value: "Tataouine", label: "Tataouine" },
  { value: "Tozeur", label: "Tozeur" },
  { value: "Tunis", label: "Tunis" },
  { value: "Zaghouan", label: "Zaghouan" },
];
